# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testapp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'testapp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtestapp.proto\x12\x08grpcdemo\"\x17\n\x08Greeting\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x9b\x02\n\x05Hello\x12@\n\x14UnaryCallUnaryReturn\x12\x12.grpcdemo.Greeting\x1a\x12.grpcdemo.Greeting\"\x00\x12\x43\n\x15UnaryCallStreamReturn\x12\x12.grpcdemo.Greeting\x1a\x12.grpcdemo.Greeting\"\x00\x30\x01\x12\x43\n\x15StreamCallUnaryReturn\x12\x12.grpcdemo.Greeting\x1a\x12.grpcdemo.Greeting\"\x00(\x01\x12\x46\n\x16StreamCallStreamReturn\x12\x12.grpcdemo.Greeting\x1a\x12.grpcdemo.Greeting\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testapp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETING']._serialized_start=27
  _globals['_GREETING']._serialized_end=50
  _globals['_HELLO']._serialized_start=53
  _globals['_HELLO']._serialized_end=336
# @@protoc_insertion_point(module_scope)
